# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gan.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='gan.proto',
  package='pb',
  syntax='proto3',
  serialized_options=b'Z?github.com/websitefingerprinting/wfdef/transports/wfgan/grpc/pb',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\tgan.proto\x12\x02pb\"\x1e\n\x0bGANResponse\x12\x0f\n\x07packets\x18\x01 \x03(\x05\"\x19\n\nGANRequest\x12\x0b\n\x03\x61sk\x18\x01 \x01(\x05\x32;\n\rGenerateTrace\x12*\n\x05Query\x12\x0e.pb.GANRequest\x1a\x0f.pb.GANResponse\"\x00\x42\x41Z?github.com/websitefingerprinting/wfdef/transports/wfgan/grpc/pbb\x06proto3'
)




_GANRESPONSE = _descriptor.Descriptor(
  name='GANResponse',
  full_name='pb.GANResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='packets', full_name='pb.GANResponse.packets', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=47,
)


_GANREQUEST = _descriptor.Descriptor(
  name='GANRequest',
  full_name='pb.GANRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ask', full_name='pb.GANRequest.ask', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=74,
)

DESCRIPTOR.message_types_by_name['GANResponse'] = _GANRESPONSE
DESCRIPTOR.message_types_by_name['GANRequest'] = _GANREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GANResponse = _reflection.GeneratedProtocolMessageType('GANResponse', (_message.Message,), {
  'DESCRIPTOR' : _GANRESPONSE,
  '__module__' : 'gan_pb2'
  # @@protoc_insertion_point(class_scope:pb.GANResponse)
  })
_sym_db.RegisterMessage(GANResponse)

GANRequest = _reflection.GeneratedProtocolMessageType('GANRequest', (_message.Message,), {
  'DESCRIPTOR' : _GANREQUEST,
  '__module__' : 'gan_pb2'
  # @@protoc_insertion_point(class_scope:pb.GANRequest)
  })
_sym_db.RegisterMessage(GANRequest)


DESCRIPTOR._options = None

_GENERATETRACE = _descriptor.ServiceDescriptor(
  name='GenerateTrace',
  full_name='pb.GenerateTrace',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=76,
  serialized_end=135,
  methods=[
  _descriptor.MethodDescriptor(
    name='Query',
    full_name='pb.GenerateTrace.Query',
    index=0,
    containing_service=None,
    input_type=_GANREQUEST,
    output_type=_GANRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_GENERATETRACE)

DESCRIPTOR.services_by_name['GenerateTrace'] = _GENERATETRACE

# @@protoc_insertion_point(module_scope)
