// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.15.7
// source: gan.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GANResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Packets []int32 `protobuf:"varint,1,rep,packed,name=packets,proto3" json:"packets,omitempty"`
}

func (x *GANResponse) Reset() {
	*x = GANResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gan_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GANResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GANResponse) ProtoMessage() {}

func (x *GANResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gan_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GANResponse.ProtoReflect.Descriptor instead.
func (*GANResponse) Descriptor() ([]byte, []int) {
	return file_gan_proto_rawDescGZIP(), []int{0}
}

func (x *GANResponse) GetPackets() []int32 {
	if x != nil {
		return x.Packets
	}
	return nil
}

type GANRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ask int32 `protobuf:"varint,1,opt,name=ask,proto3" json:"ask,omitempty"`
}

func (x *GANRequest) Reset() {
	*x = GANRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gan_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GANRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GANRequest) ProtoMessage() {}

func (x *GANRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gan_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GANRequest.ProtoReflect.Descriptor instead.
func (*GANRequest) Descriptor() ([]byte, []int) {
	return file_gan_proto_rawDescGZIP(), []int{1}
}

func (x *GANRequest) GetAsk() int32 {
	if x != nil {
		return x.Ask
	}
	return 0
}

var File_gan_proto protoreflect.FileDescriptor

var file_gan_proto_rawDesc = []byte{
	0x0a, 0x09, 0x67, 0x61, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22,
	0x27, 0x0a, 0x0b, 0x47, 0x41, 0x4e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52,
	0x07, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x22, 0x1e, 0x0a, 0x0a, 0x47, 0x41, 0x4e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x73, 0x6b, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x03, 0x61, 0x73, 0x6b, 0x32, 0x3b, 0x0a, 0x0d, 0x47, 0x65, 0x6e, 0x65,
	0x72, 0x61, 0x74, 0x65, 0x54, 0x72, 0x61, 0x63, 0x65, 0x12, 0x2a, 0x0a, 0x05, 0x51, 0x75, 0x65,
	0x72, 0x79, 0x12, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x41, 0x4e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x41, 0x4e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x41, 0x5a, 0x3f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x77, 0x65, 0x62, 0x73, 0x69, 0x74, 0x65, 0x66, 0x69, 0x6e, 0x67, 0x65,
	0x72, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x69, 0x6e, 0x67, 0x2f, 0x77, 0x66, 0x64, 0x65, 0x66, 0x2f,
	0x74, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x2f, 0x77, 0x66, 0x67, 0x61, 0x6e,
	0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gan_proto_rawDescOnce sync.Once
	file_gan_proto_rawDescData = file_gan_proto_rawDesc
)

func file_gan_proto_rawDescGZIP() []byte {
	file_gan_proto_rawDescOnce.Do(func() {
		file_gan_proto_rawDescData = protoimpl.X.CompressGZIP(file_gan_proto_rawDescData)
	})
	return file_gan_proto_rawDescData
}

var file_gan_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_gan_proto_goTypes = []interface{}{
	(*GANResponse)(nil), // 0: pb.GANResponse
	(*GANRequest)(nil),  // 1: pb.GANRequest
}
var file_gan_proto_depIdxs = []int32{
	1, // 0: pb.GenerateTrace.Query:input_type -> pb.GANRequest
	0, // 1: pb.GenerateTrace.Query:output_type -> pb.GANResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gan_proto_init() }
func file_gan_proto_init() {
	if File_gan_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gan_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GANResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gan_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GANRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gan_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gan_proto_goTypes,
		DependencyIndexes: file_gan_proto_depIdxs,
		MessageInfos:      file_gan_proto_msgTypes,
	}.Build()
	File_gan_proto = out.File
	file_gan_proto_rawDesc = nil
	file_gan_proto_goTypes = nil
	file_gan_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// GenerateTraceClient is the client API for GenerateTrace service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GenerateTraceClient interface {
	Query(ctx context.Context, in *GANRequest, opts ...grpc.CallOption) (*GANResponse, error)
}

type generateTraceClient struct {
	cc grpc.ClientConnInterface
}

func NewGenerateTraceClient(cc grpc.ClientConnInterface) GenerateTraceClient {
	return &generateTraceClient{cc}
}

func (c *generateTraceClient) Query(ctx context.Context, in *GANRequest, opts ...grpc.CallOption) (*GANResponse, error) {
	out := new(GANResponse)
	err := c.cc.Invoke(ctx, "/pb.GenerateTrace/Query", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GenerateTraceServer is the server API for GenerateTrace service.
type GenerateTraceServer interface {
	Query(context.Context, *GANRequest) (*GANResponse, error)
}

// UnimplementedGenerateTraceServer can be embedded to have forward compatible implementations.
type UnimplementedGenerateTraceServer struct {
}

func (*UnimplementedGenerateTraceServer) Query(context.Context, *GANRequest) (*GANResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Query not implemented")
}

func RegisterGenerateTraceServer(s *grpc.Server, srv GenerateTraceServer) {
	s.RegisterService(&_GenerateTrace_serviceDesc, srv)
}

func _GenerateTrace_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GANRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GenerateTraceServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.GenerateTrace/Query",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GenerateTraceServer).Query(ctx, req.(*GANRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GenerateTrace_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.GenerateTrace",
	HandlerType: (*GenerateTraceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Query",
			Handler:    _GenerateTrace_Query_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gan.proto",
}
